//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietDichVu()
        {
            this.ThongTinDangKies = new HashSet<ThongTinDangKy>();
        }
    
        public int MaCT { get; set; }
        public string TenCT { get; set; }
        public string MaGoi { get; set; }
        public string MaDV { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual GoiDichVu GoiDichVu { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDangKy> ThongTinDangKies { get; set; }
    }
}
