//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.ThongTinDangKies = new HashSet<ThongTinDangKy>();
        }
    
        public int MaKH { get; set; }
        public string HoKH { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<double> ChiTieu { get; set; }
        public Nullable<double> SoTienTK { get; set; }
        public string SDT { get; set; }
        public string MaLoai { get; set; }
    
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDangKy> ThongTinDangKies { get; set; }
    }
}
